//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class municipality
    {
        public int Idmunicipality { get; set; }
        public string Names { get; set; }
        public double Latitude { get; set; }
        public double Longitud { get; set; }
    }
}
